todolist-localstorage:new branch
Sergei181294/Gulyako_project_js pull request #1
Opened 2022-11-21 18:24 UTC by Sergei181294

2022-11-21 20:50 UTC, vledyaev requested changes

2022-11-21 20:50 UTC, vledyaev commented on index.html
> +              <div class="modeAndFiltering">
Не очень название класса. И где-то ты название класса через дефис пишешь, а где-то разным регистром. Определить и используй что-то одно.

2022-11-21 20:50 UTC, vledyaev commented on index.html
> +       <section class="box_2">
Плохое название класса, подумай за что отвечает эта секция и сделай нормальное название. Тоже самое и для `box` класса

2022-11-21 20:50 UTC, vledyaev commented on index.html
> +                            <input class="new-task-input" id="first-input" type="text" name="nameTask"
лучше для id использовать более понятное значение. Например id="task-name"

2022-11-21 20:50 UTC, vledyaev commented on store.js
> +}
это лучше вынести в `init` метод

2022-11-21 20:50 UTC, vledyaev commented on store.js
> +       anotherTask(taskName, describeTask, completed, importance) {
названия методов должны содержать глаголы. Лучше `addTask`

2022-11-21 20:50 UTC, vledyaev commented on style.css
> +       --bg-bd: #374151;
названия переменных должны быть понятными не только тебе =)

2022-11-21 20:50 UTC, vledyaev commented on style.css
> +       margin: 0;
разве у всех элементов отступ не 0 по умолчанию? Для чего это здесь?

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +                            <div>
Исправь выравнивание, непонятно где этот div заканчивается

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +                     const checked_2 = task.importance ? "checked" : "";
очень плохое название переменной. Лучше уже эту логику прям в разметку в строке перенести. Т.е. `{task.importance ? "checked" : ""}`

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +              console.log(todos.tasks)
не забывай убирать все `console.log` перед тем, как пушить что-то, т.к. это только для дебага использоваться должно

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +              ul.classList.add("taskContainer");
это список, значит он содержит несколько тасок. тогда название класса логичнее сделать `tasksContainer`

2022-11-21 20:50 UTC, vledyaev commented on store.js
> +                     importance,
насколько я понимаю, `importance`это булево значение. Тогда лучше назвать `important`

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +                                   <div class="descriptionTask">
лучше `taskDescription`

2022-11-21 20:50 UTC, vledyaev commented on store.js
> +                     describeTask,
Свойства объекта не должны называться с глаголов. Лучше `taskDescription`

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +const todosTemplate = {
необязательно все функции определять в объекте. Можно все, включая константы сверху обернуть в самовызывающуюся функцию.

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +              divContent.addEventListener("click", (e) => {
я бы посоветовал обработчики событий вынести в отдельные функции с названиями типа `removeTaskHandler` а все вызовы addEventListener собрал в каком нибудь месте разом.

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +                     if (e.target.type === "submit") {
зачем эта проверка?

2022-11-21 20:50 UTC, vledyaev commented on store.js
> +       removeTask(taskId) {
Для этого метода ты вызываешь localstorage внутри, для anotherTask вызываешь localstorage вне метода. Делай либо так, либо так, а не везде по-разному

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +              }
```suggestion
              if (todo) { 
                  todo.completed = !todo.completed
              }
              storage.setTodos(todos.tasks)
          
```

2022-11-21 20:50 UTC, vledyaev commented on index.js
> +              }
```suggestion
              if (task) { 
                  task.importance = !task.importance
              }
              storage.setTodos(todos.tasks)
```

2022-11-22 08:07 UTC, Sergei181294 commented on index.html
> +              <div class="modeAndFiltering">
ок, переделаю)

2022-11-22 08:30 UTC, Sergei181294 commented on index.html
> +       <section class="box_2">
ок, согласен

2022-11-22 08:49 UTC, Sergei181294 commented on index.html
> +                            <input class="new-task-input" id="first-input" type="text" name="nameTask"
ок, изменил

2022-11-22 08:57 UTC, Sergei181294 commented on style.css
> +       --bg-bd: #374151;
> названия переменных должны быть понятными не только тебе =)

так а норм, если они тогда будут длинные или состоять из целого слоова типа --bg-body или --bg-page?

2022-11-22 09:03 UTC, Sergei181294 commented on style.css
> +       margin: 0;
> разве у всех элементов отступ не 0 по умолчанию? Для чего это здесь?

ну вроде нет, в инете написано так (для <body> по умолчанию margin задан как 8px; для списков <ul>, <ol>, <dl> margin-top и margin-bottom заданы как 1em; для <blockquote> и <figure> margin-left и margin-right заданы как 40px.)
если убираю margin:0, то все разлетается в интерфейсе

2022-11-22 09:08 UTC, Sergei181294 commented on index.js
> +                            <div>
> Исправь выравнивание, непонятно где этот div заканчивается

согласен, исправил)

2022-11-22 09:10 UTC, Sergei181294 commented on index.js
> +                     const checked_2 = task.importance ? "checked" : "";
ок, переделал)

> очень плохое название переменной. Лучше уже эту логику прям в разметку в строке перенести. Т.е. `{task.importance ? "checked" : ""}`

ок, переделал)

2022-11-22 09:11 UTC, Sergei181294 commented on index.js
> +              console.log(todos.tasks)
понял, упустил)

> не забывай убирать все `console.log` перед тем, как пушить что-то, т.к. это только для дебага использоваться должно

2022-11-22 09:13 UTC, Sergei181294 commented on index.js
> +              ul.classList.add("taskContainer");
логично)

> это список, значит он содержит несколько тасок. тогда название класса логичнее сделать `tasksContainer`

2022-11-22 09:23 UTC, Sergei181294 commented on store.js
> +                     importance,
ок

2022-11-22 10:03 UTC, Sergei181294 commented on store.js
> +}
сделал

2022-11-22 10:03 UTC, Sergei181294 commented on store.js
> +       anotherTask(taskName, describeTask, completed, importance) {
готово

2022-11-22 10:29 UTC, Sergei181294 commented on index.js
> +                                   <div class="descriptionTask">
> лучше `taskDescription`

я удалю, он у мееня не используется вообще

2022-11-22 10:30 UTC, Sergei181294 commented on store.js
> +                     describeTask,
> Свойства объекта не должны называться с глаголов. Лучше `taskDescription`

исправил

2022-11-22 11:30 UTC, Sergei181294 commented on index.js
> +const todosTemplate = {
> необязательно все функции определять в объекте. Можно все, включая константы сверху обернуть в самовызывающуюся функцию.

а так плохо смотрится или для чего это?

2022-11-22 12:06 UTC, Sergei181294 commented on index.js
> +              }
прикольно, я бы не додумался)

>

2022-11-24 08:20 UTC, closed without merging